### ISSUE TITLE
No autoplay in playlists

### ISSUE THREAD

**Issue by TomberWolf** [yuliskov/SmartYouTubeTV#278] opened 2019-04-23 16:16 UTC
Autoplay doesn't work for playlists

6.16.98

**Comment by ghzgod** [comment] 2019-06-07 17:56
I second this.  It plays a video but not the one in the playlist. You have to manually select the next video in the playlist.

**Comment by yuliskov** [comment] 2019-06-08 12:44
duplicate of #271

**Closed as completed by yuliskov** 2019-06-08 12:44 UTC
