### ISSUE TITLE
Pro main and pro alt problem

### ISSUE THREAD

**Issue by chayank69** [yuliskov/SmartYouTubeTV#298] opened 2019-06-07 19:32 UTC
Pro main and pro alt launcher having problem playing music video.
Pro main is stuck at loading while pro alt the music play but its all black no video.
Try the same video with the lite main laincher, and the video play with no problem.
But the lite version video quality is not as good as the pro at the same resolution.
The pro used to work like charm but after updates it stop it's miracle.

**Comment by yuliskov** [comment] 2019-06-07 19:40
duplicate of #294

**Closed as completed** 2019-06-07 19:40 UTC
