### ISSUE TITLE
Fire TV Stick: Lagging/Stuttering after >30 Minutes Playback

### ISSUE THREAD

**Issue by molabs** [yuliskov/SmartYouTubeTV#133] opened 2018-06-24 10:18 UTC
Version: 6.12.96 (Also affects the versions before that)
Fire TV Stick 1. Generation
If I watch a lets play of 45-60 minutes, the video usually starts after ~30 minutes to lag/stutter and the app is barely usable. Reproducible on 2 FireTV Sticks.

**Comment by yuliskov** [comment] 2018-09-22 20:42
duplicate of #74

**Closed by yuliskov** 2018-09-22 20:42 UTC
Labels: bug
