### ISSUE TITLE
Recent build broke cast volume control from phone

### ISSUE THREAD

**Issue by EpochalEngineer** [yuliskov/SmartYouTubeTV#156] opened 2018-09-15 05:24 UTC
Have had this on my Fire TV Stick for a while and recently decided to upgrade to 6.14.23 due to a random playback error (not sure if upgrading was necessary) and now the casting volume control doesn't work anymore.  Now the volume is always at max (and interestingly, the phones see and peg the volume at silent).

Not positive which version I was on before if anyone know which version I should revert to.

**Comment by yuliskov** [comment] 2018-09-15 07:39
Hi. Older releases can be found here: https://github.com/yuliskov/SmartYouTubeTV/releases
I'll appreciate if you find one that is working best for you.

**Comment by yuliskov** [comment] 2018-09-22 20:29
duplicate of #38

**Closed by yuliskov** 2018-09-22 20:29 UTC
Labels: bug
