### ISSUE TITLE
Limit video warnings Click to exit the program

### ISSUE THREAD

**Issue by xiaoxihu2017** [yuliskov/SmartYouTubeTV#157] opened 2018-09-22 06:00 UTC
Two xiaomi TV 55 and xiaomi TV 65 clients updated to 6.14.26/6.14.27
After the installation is complete, the first click to restrict the video warning can be played, and click again to exit the client.
lease help check and fix, thank you

**Comment by yuliskov** [comment] 2018-09-22 10:47
Duplicate of #153

**Closed by yuliskov** 2018-09-22 10:47 UTC
