### ISSUE TITLE
Variable Playback Speed

### ISSUE THREAD

**Issue by neoman4426** [yuliskov/SmartYouTubeTV#104] opened 2018-04-15 10:45 UTC
Not sure if it's possible to add since near as I can tell there's no way to do it from the web version of the TV interface, but would it be possible to add a playback speed option? On the standard browser interface speed can be set between 1/4 and 2x speed either through the settings cog or using < and > keys. I prefer to play most videos at 2x speed to save time, but currently the choice as far as I can tell is having a decent remote interface (standard AndroidTV app, this one, etc) but locked to 1x speed, or pulling up whatever videos in a browser on device and getting all the speed options but requiring I pull out a mouse. There are browser addons that give an even greater variability of speed, allowing both granular controls (could set it to 1.8x or whatever for instance rather than going with 1.5 or 2 the dropdown offers) as well as increasing the cap (certain videos are perfectly watchable at 3x for instance), not sure if that's helpful, never tried the one I used to use out on the TV interface to see if that would work there. 

==EDIT== Not sure if it would be helpful in implementing it, but at least one extension does indeed seem to work to change speed in a desktop browser pointing to the TV interface page, not the one I used to use (that one had a toolbar icon that persisted between visits, this one has an address bar icon that seems to go back to 1x if you go leave and come back) but the first one I found looking for an example to post, https://addons.mozilla.org/en-US/firefox/addon/youtube-speed-controller/?src=search

**Comment by yuliskov** [comment] 2018-05-17 07:15
duplicate of #73

**Closed by yuliskov** 2018-05-17 07:15 UTC
Labels: enhancement
