### ISSUE TITLE
Black Screeen on Fire TV Stick 1st Gen

### ISSUE THREAD

**Issue by na7q** [yuliskov/SmartYouTubeTV#140] opened 2018-07-25 16:19 UTC
After installing the app and trying to "cast" from my devices, the screen goes black and does not load any videos or do anything until disconnecting. Once disconnected I can reload the app to see YouTube. But still cannot cast anything to the TV without having a black screen.

**Comment by yuliskov** [comment] 2018-09-22 20:43
duplicate of #38

**Closed by yuliskov** 2018-09-22 20:43 UTC
Labels: bug, help wanted
