### ISSUE TITLE
6.16.98 FTV 4K video freezes for 5s while audio is running

### ISSUE THREAD

**Issue by anubis-genix** [yuliskov/SmartYouTubeTV#286] opened 2019-05-16 19:25 UTC
Using Pro ALT and on every video I start the first frame is freezing for about 5 seconds while the audio is playing in the background. The same goes for skipping or rewinding in the video.

**Comment by yuliskov** [comment] 2019-06-08 12:49
duplicate of #243

**Closed as completed by yuliskov** 2019-06-08 12:49 UTC
