### ISSUE TITLE
App chooses wrong stream quality (higher than device is capable of playing)

### ISSUE THREAD

**Issue by Maikell84** [yuliskov/SmartYouTubeTV#31] opened 2017-12-06 15:17 UTC
I have an Allwinner A33 - device with Android 5.1.1. It has a 7 inch screen which has a physical resolution of `1024x600`:

    root@astar-yh:/ # wm size
    Physical size: 1024x600

I am using the "4k-profile", since the others don't work properly, or require Crosswalk, which is not installed.

When I install the app (latest version 6.10.17), it plays the videos. **However it often takes the FullHD stream!** I have verified this, by navigating to "Quality" -> "Video" while the video was playing. (Please see attached screenshot)

![screen](https://user-images.githubusercontent.com/12297422/33668363-d319f320-da9f-11e7-9d24-ce819d718994.png)

- It should not download a higher stream-quality, than the device is capable of playing.
- While this is not fixed: Can you please tell me where I could insert a monkey patch, to fix this for my device?

Thank you!

This is an awesome app by the way.

**Comment by yuliskov** [comment] 2017-12-08 10:49
Hi. There is problems down there.

1. Android devices unable to report video output resolution. All I can get is interface resolution. One may differs depending on device. For example 4K  boxes claim that they have 1080p resolution.
2. Another chance would be to use codec capabilities. Yes, I can get list of supported codecs for your device. But again, most of device do it wrongly. I tested myself. Devices that unable to play specific codec/resolution often report that they can. 

As you can see both soluton aren't perfect.

Resume. For now, the best practice would be to choose the resolution manually. All that I can promise is to maintain selected quality as long as possible.

**Comment by Maikell84** [comment] 2017-12-11 09:54
Hi Thank you for your detailled explanation. Ok if you cannot get the real video-output resolution it doesn't make sense do implement this feature. 

Does a variable make sense to you, where you set the maximum possible stream-quality in the code? Maybe a static enum with values: 240p, 360p, 480p, ... and so on which defaults to 4k.

For my special use-case I have resolved it, by not displaying resolutions higher than 720p in `TrackSelectionHelper.java`, and by limiting the stream-Quality in `PlayerActivity.java`

I think you can close this issue. 
Thank you.

**Comment by yuliskov** [comment] 2017-12-11 13:08
Hi. I could apply fix specifically for your device. I need the patch and device id from CPU-Z.

**Comment by yuliskov** [comment] 2017-12-24 21:24
Closed. Can't do precise resolution detection on api < 23.

**Comment by yuliskov** [comment] 2018-09-22 20:38
duplicate of #99

**Closed by yuliskov** 2018-09-22 20:38 UTC
Labels: bug
