### ISSUE TITLE
Main interface zoom display 2/3 of the interface.

### ISSUE THREAD

**Issue by sisx** [yuliskov/SmartYouTubeTV#60] opened 2018-01-15 06:26 UTC
TV Model: Coocaa 50U3B (4K)
Android version: seems to be Android 5.0
issue:
1. Open the application to select MiTV 4k, can log in Google account, but also to play the video. However, in the video back, you can not fully display the main interface, zoom display 2/3 of the interface.
2. The program crashes randomly when exiting the video.
3. In the main program interface, press the Back button occasionally does not appear to exit the program button.

**Comment by yuliskov** [comment] 2018-01-15 07:07
@sisx please, add version of the build

**Comment by yuliskov** [comment] 2018-01-15 10:32
@sisx is this problem persists on the latest build?
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.46/SmartYouTubeTV_Orig_v6.12.46_r.apk

**Comment by yuliskov** [comment] 2018-01-16 03:20
@sisx seems like this duplicate of https://github.com/yuliskov/SmartYouTubeTV/issues/52

**Comment by yuliskov** [comment] 2018-02-03 19:11
Seems duplicate of the bug https://github.com/yuliskov/SmartYouTubeTV/issues/52

**Closed by yuliskov** 2018-02-03 19:11 UTC
Labels: invalid
