### ISSUE TITLE
Long "Loading..." after pause and play again

### ISSUE THREAD

**Issue by byaka** [yuliskov/SmartYouTubeTV#90] opened 2018-03-18 12:04 UTC
Anyone has same problem? or its limitation of used player?

**Comment by yuliskov** [comment] 2018-03-21 12:21
@byaka this is definitely a case where system player cause such behavior. I'm not sure that I can deal with it.

**Comment by byaka** [comment] 2018-03-22 09:58
crap.. thx for info
anyway its best youtube player for smart-tv :)

**Comment by yuliskov** [comment] 2018-09-23 07:58
duplicate of #83

**Closed by yuliskov** 2018-09-23 07:58 UTC
Labels: bug
