### ISSUE TITLE
Unable to Instantiate Amlogic Decoder

### ISSUE THREAD

**Issue by pystIC** [yuliskov/SmartYouTubeTV#51] opened 2018-01-12 07:48 UTC
Hi,

I use a Mibox international and when i get into a video and push the back button to search for another and start the new vid sometimes it will throw up an unable to instantiate amlogic decoder and wont play again till I exit and stop the app.

**Comment by yuliskov** [comment] 2018-01-12 08:09
@pystIC please, provide additional info. What codec/resolution was selected at the moment when bug happen? Also, it's worth mention your device's Android version.

**Comment by pystIC** [comment] 2018-01-12 09:05
I believe it was playing 1080p vids. I was just trying the app out trying random vids Like Taylor Swift - Look What You Made Me Do. I think it’s VP9. Android TV 7.0

**Comment by yuliskov** [comment] 2018-01-12 09:15
@pystIC many thanks for the info. Here the test build. It has different video output. Interested to know is there any changes compare to current release.
https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.12.41/SmartYouTubeTV_Orig_v6.12.41_r.apk

**Comment by yuliskov** [comment] 2018-02-03 19:09
Duplicate of bug https://github.com/yuliskov/SmartYouTubeTV/issues/53

**Closed by yuliskov** 2018-02-03 19:09 UTC
Labels: bug
