### ISSUE TITLE
Somtimes video lag 3 seconds in Mibox3 enhance version

### ISSUE THREAD

**Issue by frankieyen** [yuliskov/SmartYouTubeTV#92] opened 2018-03-21 08:55 UTC
half years ago , I used smartyoutubetv , it works fine but can't watch live stream channel .
about one month ago , I update my smartyoutubetv  , now live steam channel works ,
but Somtimes video lag 3 seconds (about 1 time per 10 mins) , I used 6.12.58 - 79 , It all have this problem ,
I'm not sure how to fix it . Just submit this try to get solution , thanks for your effort .

**Comment by frankieyen** [comment] 2018-03-22 01:08
After install crosswalklib arm64 , the situation seems dissapear , I will keep watching .

reference : https://forum.xda-developers.com/fire-tv/development/app-youtube-tv-app-fire-tv-t3757074

**Comment by frankieyen** [comment] 2018-03-27 10:04
oh oh , after watching for one week ... this situation still going ... I can't fix it by myself ...I will try the newest version again . Thanks .

**Comment by yuliskov** [comment] 2018-09-22 19:44
duplicate of #74

**Closed by yuliskov** 2018-09-22 19:44 UTC
Labels: bug
