### ISSUE TITLE
Limit video warning clicks and agree to exit

### ISSUE THREAD

**Issue by xiaoxihu2017** [yuliskov/SmartYouTubeTV#153] opened 2018-09-10 07:15 UTC
xiaomi TV 55  and xiaomi TV 65                   6.14.20and6.14.10
Limit video warning clicks and agree to exit.
Click Clear History to exit the program.
Please look at the trouble video.  https://youtu.be/-enGNRvB1tA

**Comment by yuliskov** [comment] 2018-09-22 10:59
@xiaoxihu2017 please, switch app to English and then record this video again

**Comment by yuliskov** [comment] 2018-09-22 22:45
Seems like duplicate of #119

**Comment by xiaoxihu2017** [comment] 2018-09-26 02:36
@yuliskov   Play the warning, click, agree, the program exits.
Video English warning content:
Content Warning   This video may be inappropriate for some users.

**Comment by yuliskov** [comment] 2018-09-26 07:31
@xiaoxihu2017 thanks for reply. Is there other users that experience the same? Unfortunately, I can't reproduce this behavior on my setup. I could only guess about sources of the problem. My first assumption is that your account's age setting could cause this behavior. Secondly, I would assume that problem is vpn related.

**Comment by yuliskov** [comment] 2018-10-12 11:53
@xiaoxihu2017 does the bug still appear? If so, then please record video (like above) again but before do switch app language to English. I barely can translate from Chinese.

**Comment by yuliskov** [comment] 2018-10-20 10:33
Closed for now, since not enough input from the user

**Closed by yuliskov** 2018-10-20 10:33 UTC
Labels: bug
