### ISSUE TITLE
connect Smat youtube TV whit phone app

### ISSUE THREAD

**Issue by salvattore** [yuliskov/SmartYouTubeTV#137] opened 2018-07-10 17:09 UTC
there are some problems when i connect the current version of smart youtube TV on my ATVIO smart  TV whit the youtube android app for cell phones, for example; 

1.- when i try to change a video while im connected to my cell phone, Smart youtube TV crashes, and i need to disconnect my phone of the tv if i want to change of video.

2.- it slows down my tv, no matter which version im using (720, 1080, 4K or alt ver), every time i connect my phone to the TV this happens.

can i do something to fix this issues?

**Comment by yuliskov** [comment] 2018-09-22 20:41
duplicate of #38

**Closed by yuliskov** 2018-09-22 20:41 UTC
Labels: bug
