### ISSUE TITLE
smartyoutubetv doesn't work on mitv4

### ISSUE THREAD

**Issue by piao1220** [yuliskov/SmartYouTubeTV#130] opened 2018-06-09 13:34 UTC
my new mitv4 tvset have installed crosswalk project and all vesions of smart youtube tv you developed,however,no content displays.

![tim 20180609213257](https://user-images.githubusercontent.com/40118361/41192181-d5f8c46c-6c2c-11e8-9b17-c9e4a688f6c0.jpg)

**Comment by iamggs** [comment] 2018-06-09 14:37
I also have this problem, it will appear in MITV mode on my Phicomm T1 tvbox.

**Comment by yuliskov** [comment] 2018-06-09 14:40
duplicate of #95

**Closed by yuliskov** 2018-06-09 14:40 UTC
