### ISSUE TITLE
Video often gets out of sync with the audio

### ISSUE THREAD

**Issue by ratratrats** [yuliskov/SmartYouTubeTV#204] opened 2018-12-04 03:57 UTC
Hi, I'm on a Gen 2 Amazom Fire TV stick.
A lot of the time, the audio seems to not sync up with the video. It's definitely not the video itself, since the issue is fixed by pausing and unpausing. I'm on the 1080p main build.

**Comment by yuliskov** [comment] 2018-12-04 04:10
duplicate of #74

**Closed by yuliskov** 2018-12-04 04:10 UTC
